// Curated list of popular interest categories
// Shared between onboarding and profile editing
export const AVAILABLE_INTERESTS = [
  'Art',
  'Baking',
  'Basketball',
  'Beach',
  'Books',
  'Business',
  'Camping',
  'Cinema',
  'Coffee',
  'Comedy',
  'Concerts',
  'Cooking',
  'Cycling',
  'Dance',
  'Design',
  'Dogs',
  'Entrepreneurship',
  'Fashion',
  'Festivals',
  'Fitness',
  'Foodie',
  'Football',
  'Gaming',
  'Gardening',
  'Golf',
  'Hiking',
  'Music',
  'Nature',
  'Nightlife',
  'Pets',
  'Photography',
  'Podcasts',
  'Reading',
  'Running',
  'Science',
  'Soccer',
  'Sports Fan',
  'Tech',
  'Tennis',
  'Travel',
  'Volunteering',
  'Wine & Spirits',
  'Writing',
  'Yoga',
].sort(); // Alphabetically sorted for easy browsing
